var annotated_dup =
[
    [ "AnalogInput", "classAnalogInput.html", null ],
    [ "AnalogModuleV1_0", "classAnalogModuleV1__0.html", "classAnalogModuleV1__0" ],
    [ "AnalogOutput", "classAnalogOutput.html", "classAnalogOutput" ],
    [ "BusModuleV1_0", "classBusModuleV1__0.html", "classBusModuleV1__0" ],
    [ "CANCore", "classCANCore.html", "classCANCore" ],
    [ "CANInterface", "classCANInterface.html", null ],
    [ "CANTramCore", "classCANTramCore.html", null ],
    [ "CANTramModule", "classCANTramModule.html", "classCANTramModule" ],
    [ "DigitalInput", "classDigitalInput.html", null ],
    [ "DigitalModuleV1_0", "classDigitalModuleV1__0.html", "classDigitalModuleV1__0" ],
    [ "DigitalOutput", "classDigitalOutput.html", null ],
    [ "ESP32_CANCore", "classESP32__CANCore.html", "classESP32__CANCore" ],
    [ "ESP32_I2CCore", "classESP32__I2CCore.html", "classESP32__I2CCore" ],
    [ "ESP32_UART", "classESP32__UART.html", "classESP32__UART" ],
    [ "ESP32PWMCore", "classESP32PWMCore.html", "classESP32PWMCore" ],
    [ "HardwareResource", "classHardwareResource.html", "classHardwareResource" ],
    [ "I2CCore", "classI2CCore.html", "classI2CCore" ],
    [ "I2CInterface", "classI2CInterface.html", null ],
    [ "Interface", "classInterface.html", null ],
    [ "ISO1H816G", "classISO1H816G.html", null ],
    [ "ISO1I813T", "classISO1I813T.html", "classISO1I813T" ],
    [ "MainModuleV1_0", "classMainModuleV1__0.html", "classMainModuleV1__0" ],
    [ "MAX22531", "classMAX22531.html", "classMAX22531" ],
    [ "OutputDefinition", "classOutputDefinition.html", "classOutputDefinition" ],
    [ "OutputProvider", "classOutputProvider.html", "classOutputProvider" ],
    [ "PWMCore", "classPWMCore.html", "classPWMCore" ],
    [ "PWMOutputProvider", "classPWMOutputProvider.html", "classPWMOutputProvider" ],
    [ "RelaisInterface", "classRelaisInterface.html", null ],
    [ "RelaisModuleV1_0", "classRelaisModuleV1__0.html", "classRelaisModuleV1__0" ],
    [ "SPIChip", "classSPIChip.html", null ],
    [ "UARTCore", "classUARTCore.html", "classUARTCore" ],
    [ "UARTInterface", "classUARTInterface.html", null ],
    [ "UARTProvider", "classUARTProvider.html", "classUARTProvider" ]
];