var annotated_dup =
[
    [ "AnalogInput", "de/d85/class_analog_input.html", null ],
    [ "AnalogModuleV1_0", "d4/d06/class_analog_module_v1__0.html", "d4/d06/class_analog_module_v1__0" ],
    [ "AnalogOutput", "df/de2/class_analog_output.html", "df/de2/class_analog_output" ],
    [ "BusModuleV1_0", "dd/dcb/class_bus_module_v1__0.html", "dd/dcb/class_bus_module_v1__0" ],
    [ "CANCore", "d9/d06/class_c_a_n_core.html", "d9/d06/class_c_a_n_core" ],
    [ "CANInterface", "d8/db6/class_c_a_n_interface.html", null ],
    [ "CANTramCore", "d9/d4b/class_c_a_n_tram_core.html", null ],
    [ "CANTramModule", "d2/dee/class_c_a_n_tram_module.html", "d2/dee/class_c_a_n_tram_module" ],
    [ "DigitalInput", "db/db0/class_digital_input.html", null ],
    [ "DigitalModuleV1_0", "d4/ddb/class_digital_module_v1__0.html", "d4/ddb/class_digital_module_v1__0" ],
    [ "DigitalOutput", "dd/da6/class_digital_output.html", null ],
    [ "ESP32_CANCore", "d6/d24/class_e_s_p32___c_a_n_core.html", "d6/d24/class_e_s_p32___c_a_n_core" ],
    [ "ESP32_I2CCore", "d0/d97/class_e_s_p32___i2_c_core.html", "d0/d97/class_e_s_p32___i2_c_core" ],
    [ "ESP32_UART", "dc/deb/class_e_s_p32___u_a_r_t.html", "dc/deb/class_e_s_p32___u_a_r_t" ],
    [ "ESP32PWMCore", "da/d75/class_e_s_p32_p_w_m_core.html", "da/d75/class_e_s_p32_p_w_m_core" ],
    [ "HardwareResource", "d2/d03/class_hardware_resource.html", "d2/d03/class_hardware_resource" ],
    [ "I2CCore", "d0/dd5/class_i2_c_core.html", "d0/dd5/class_i2_c_core" ],
    [ "I2CInterface", "df/d11/class_i2_c_interface.html", null ],
    [ "Interface", "de/d95/class_interface.html", null ],
    [ "ISO1H816G", "d8/d9a/class_i_s_o1_h816_g.html", null ],
    [ "ISO1I813T", "d7/d6e/class_i_s_o1_i813_t.html", "d7/d6e/class_i_s_o1_i813_t" ],
    [ "MainModuleV1_0", "dd/dff/class_main_module_v1__0.html", "dd/dff/class_main_module_v1__0" ],
    [ "MAX22531", "d7/dd1/class_m_a_x22531.html", "d7/dd1/class_m_a_x22531" ],
    [ "OutputDefinition", "db/dc2/class_output_definition.html", "db/dc2/class_output_definition" ],
    [ "OutputProvider", "d6/d8a/class_output_provider.html", "d6/d8a/class_output_provider" ],
    [ "PWMCore", "d2/deb/class_p_w_m_core.html", "d2/deb/class_p_w_m_core" ],
    [ "PWMOutputProvider", "dc/d46/class_p_w_m_output_provider.html", "dc/d46/class_p_w_m_output_provider" ],
    [ "RelaisInterface", "d0/de8/class_relais_interface.html", null ],
    [ "RelaisModuleV1_0", "d0/d4d/class_relais_module_v1__0.html", "d0/d4d/class_relais_module_v1__0" ],
    [ "SPIChip", "d5/d31/class_s_p_i_chip.html", null ],
    [ "UARTCore", "d4/da9/class_u_a_r_t_core.html", "d4/da9/class_u_a_r_t_core" ],
    [ "UARTInterface", "dd/dc4/class_u_a_r_t_interface.html", null ],
    [ "UARTProvider", "d8/d59/class_u_a_r_t_provider.html", "d8/d59/class_u_a_r_t_provider" ]
];