M48
; DRILL file {KiCad 9.0.1} date 2025-08-07T18:16:20+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-07T18:16:20+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.250
%
G90
G05
T1
X122.2Y-95.2
T2
X102.0Y-95.2
T3
X103.75Y-83.75
X196.25Y-60.75
T4
X104.61Y-61.46
X117.31Y-61.46
M30
