M48
; DRILL file {KiCad 9.0.1} date 2025-11-10T14:25:26+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-10T14:25:26+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.230
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C1.442
%
G90
G05
T1
X102.0Y-95.4
T2
X122.2Y-95.4
T3
X102.0Y-95.4
T4
X122.2Y-95.4
M30
