M48
; DRILL file {KiCad 9.0.1} date 2025-11-10T23:52:08+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-10T23:52:08+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X121.085Y-74.645
X133.125Y-74.645
T2
X82.34Y-78.35
X93.77Y-78.35
X103.02Y-78.35
X114.45Y-78.35
M30
